import type { Metadata } from "next";

import Footer from "@/components/Footer";
import Header from "@/components/Header";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main className="flex">
        <div className='flex flex-col w-full'>
          <Header/>
          <div className='flex-1'>
              {children}
          </div> 
          <Footer/>
        </div>
      </main>

  );
}
